# Generated by Django 4.2 on 2024-03-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_usertariff_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='duration',
        ),
        migrations.AddField(
            model_name='tariff',
            name='period',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Срок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость тарифа'),
        ),
    ]
