# Generated by Django 4.2 on 2024-03-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_transaction_date_alter_transaction_user_tariff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='period',
            field=models.IntegerField(choices=[(1, '1 месяц'), (3, '3 месяца'), (6, '6 месяцев'), (12, '12 месяцев')], verbose_name='Срок'),
        ),
    ]
