# Generated by Django 4.2 on 2024-03-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_tariff_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tariff',
            old_name='period',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='test_period',
        ),
        migrations.AddField(
            model_name='tariff',
            name='test_duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Пробный период'),
        ),
    ]
