# Generated by Django 4.2 on 2024-03-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_tariff_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tariff',
            old_name='duration',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='tariff',
            old_name='test_duration',
            new_name='test_period',
        ),
    ]
