# Generated by Django 4.2 on 2024-03-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_alter_usertariff_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='period',
            field=models.PositiveSmallIntegerField(verbose_name='Срок'),
        ),
    ]
