# Generated by Django 4.2 on 2024-03-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_alter_tariff_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='test_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Пробный период'),
        ),
    ]
